spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accountsapp?serverTimezone=Europe/Warsaw&useSSl=False&allowPublicKeyRetrieval=true
    username: kodilla
    password: kodilla_password
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
accountsapp:
  allow-get-accounts: true
